[workspace]
members = [
    # "bellman",
    "ff",
    "group",
    "jubjub",
    # "librustzcash",
    "pairing",
    # "zcash_client_backend",
    # "zcash_client_sqlite",
    "zcash_primitives",
    # "zcash_proofs",
]

[profile.release]
lto = true
panic = 'abort'
codegen-units = 1
