[package]
name = "zcash_client_backend"
version = "0.0.0"
authors = [
    "Jack Grigg <jack@z.cash>",
]
edition = "2018"

[dependencies]
protobuf = "2"

[build-dependencies]
protobuf-codegen-pure = "2"
